- name: update homebrew
  homebrew: update_homebrew=yes

- name: homebrew tap
  homebrew_tap:
    name: '{{ item }}'
    state: present
  loop:
    - mackerelio/mackerel-agent
    - sanemat/font
    - osx-cross/avr
    - PX4/homebrew-px4
    - aws/tap

- name: homebrew
  homebrew: name={{ item }} state=present
  loop:
    - anyenv
    #- avr-gcc
    #- avrdude
    - aws-sam-cli
    - awscli
    - cask
    - composer
    - coreutils
    - dfu-programmer
    - direnv
    - docker
    - docker-compose
    - envchain
    - fontforge
    - gcc-arm-none-eabi
    - git
    - gnu-sed
    - grep
    - htop
    - hub
    - iproute2mac
    - jq
    - mkr
    - oath-toolkit
    - peco
    - putty
    - reattach-to-user-namespace
    - ricty
    - sqlite
    - telnet
    - tig
    - tmux
    - tree
    - vim
    - w3m
    - watch
    - wget
    - zlib
    - zsh-completions

- name: pip packages
  pip: name={{ item }}
  loop:
    - powerline-status
    - requests-aws4auth
    - boto
    - ansible-lint
    - yamllint

- name: homebrew cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
    accept_external_apps: True
    install_options: 'appdir=/Applications'
  loop:
    - Franz
    - alfred
    - chatwork
    - clipy
    - cyberduck
    - enpass
    - firefox
    - gitify
    - google-chrome
    - google-japanese-ime
    - iterm2
    - karabiner
    - karabiner-elements
    - macdown
    - shiftit
    - skitch
    - slack
    - visual-studio-code
