- name: update homebrew
  homebrew: update_homebrew=yes

- name: homebrew tap
  homebrew_tap:
    name: '{{ item }}'
    state: present
  loop:
    - sanemat/font
    - osx-cross/avr
    - PX4/homebrew-px4

- name: homebrew
  homebrew: name={{ item }} state=present
  loop:
    - ansible
    #- avr-gcc
    #- avrdude
    - awscli
    - cask
    - coreutils
    - dfu-programmer
    - direnv
    - docker
    - docker-compose
    - envchain
    - fontforge
    - gcc-arm-none-eabi
    - ghq
    - git
    - gnu-sed
    - go
    - grep
    - htop
    - hub
    - iproute2mac
    - jq
    - macvim
    - neovim
    - nodebrew
    - oath-toolkit
    - openssl
    - peco
    - putty
    - pyenv
    - python
    - rbenv
    - reattach-to-user-namespace
    - ricty
    - ruby-build
    - sl
    - sqlite
    - telnet
    - terraform
    - tig
    - tmux
    - tree
    - tree
    - w3m
    - watch
    - wget
    - zlib
    - zsh
    - zsh-completions

- name: pip packages
  pip: name={{ item }}
  loop:
    - powerline-status
    - requests-aws4auth
    - boto
    - ansible-lint
    - yamllint

- name: homebrew cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
    accept_external_apps: True
    install_options: 'appdir=/Applications'
  loop:
    - Franz
    - alfred
    - chatwork
    - clipy
    - cyberduck
    - enpass
    - firefox
    - google-chrome
    - google-japanese-ime
    - iterm2
    - jasper
    - karabiner
    - karabiner-elements
    - macdown
    - messenger
    - shiftit
    - skitch
    - skype
    - slack
    - thunderbird
    - virtualbox
    - visual-studio-code
