### dotfiles
- name: setup dotfiles
  file:
    src: "${PWD}/roles/dotfiles/files/{{ item }}"
    dest: "${HOME}/{{ item }}"
    force: true
    state: link
  with_items:
      - .bashrc
      - .zshrc
      - .zlogin
      - .zlogout
      - .zshenv
      - .zpreztorc
      - .vimrc
      - .gvimrc
      - .tmux.conf
      - .commit_template

### zsh
- name: add zsh path
  become: True
  blockinfile:
    dest: /etc/shells
    insertafter: '^/bin/zsh$'
    content: /usr/local/bin/zsh

- name: change shell to zsh
  become: True
  command: chsh -s '/usrlocal/bin/zsh'
