### dotfiles
- name: setup dotfiles
  tags: dotfiles
  file:
    src: "${PWD}/roles/dotfiles/files/{{ item }}"
    dest: "${HOME}/{{ item }}"
    force: true
    state: link
  loop:
      - .bashrc
      - .zshrc
      - .zlogin
      - .zlogout
      - .zshenv
      - .zpreztorc
      - .vimrc
      - .gvimrc
      - .tigrc
      - .tmux.conf
      - .commit_template
      - .gitconfig

### mkdir
- name: mkdir tmp
  file:
    path: "${PWD}/{{ item }}"
    state: directory
  loop:
    - tmp

### karabiner
- name: karabiner config
  file: 
    src: ${PWD}/roles/dotfiles/files/.config/karabiner
    dest: ${HOME}/.config/karabiner
    state: link

### zsh
- name: add zsh path
  become: True
  blockinfile:
    dest: /etc/shells
    insertafter: '^/bin/zsh$'
    content: /usr/local/bin/zsh

- name: change shell to zsh
  become: True
  command: chsh -s '/usrlocal/bin/zsh'

- git:
    repo: git@github.com:sorin-ionescu/prezto.git
    dest: ${HOME}/.zprezto
    force: yes
    version: master
    accept_hostkey: yes

- name: link mytheme
  file:
    src: ${PWD}/roles/dotfiles/files/.zprezto/modules/prompt/external/mytheme/prompt_mytheme_setup
    dest: ${HOME}/.zprezto/modules/prompt/functions/prompt_mytheme_setup
    state: link

### vim
- name:
  file:
    path: ~/.vim/colors
    state: directory

- git:
    repo: git@github.com:Shougo/neobundle.vim
    dest: ${HOME}/.vim/bundle/neobundle.vim
    version: master
    accept_hostkey: yes

- git:
    repo: git@github.com:tomasr/molokai
    dest: /tmp/molokai
    version: master
    accept_hostkey: yes

- name: set molokai file
  copy:
    src: /tmp/molokai/colors/molokai.vim
    dest: ${HOME}/.vim/colors/molokai.vim

### tmux
- git:
    repo: git@github.com:/tmux-plugins/tpm
    dest: ${HOME}/.tmux/plugins/tpm
    version: master
    accept_hostkey: yes

### font
- name: copy ricty files
  copy:
    src: "{{ item }}"
    dest: ${HOME}/Library/Fonts/
  with_fileglob:
    - "/usr/local/Cellar/ricty/4.1.0_2/share/fonts/Ricty*"

- git:
    repo: git@github.com:Lokaltog/powerline-fontpatcher
    dest: /tmp/powerline-fontpatcher
    accept_hostkey: yes

- name: patch font powerline
  command: fontforge -lang=py -script /tmp/powerline-fontpatcher/scripts/powerline-fontpatcher /usr/local/Cellar/ricty/4.1.0_2/share/fonts/Ricty-Regular.ttf
  args:
    chdir: tmp

- name: copy powerline-patch file
  copy:
    src: tmp/Ricty Regular for Powerline.ttf
    dest: ${HOME}/Library/Fonts/
