### dotfiles
- name: setup dotfiles
  file:
    src: "${PWD}/roles/dotfiles/files/{{ item }}"
    dest: "${HOME}/{{ item }}"
    force: true
    state: link
  with_items:
      - .bashrc
      - .zshrc
      - .zlogin
      - .zlogout
      - .zshenv
      - .zpreztorc
      - .vimrc
      - .gvimrc
      - .tmux.conf
      - .commit_template

### zsh
- name: add zsh path
  become: True
  blockinfile:
    dest: /etc/shells
    insertafter: '^/bin/zsh$'
    content: /usr/local/bin/zsh

- name: change shell to zsh
  become: True
  command: chsh -s '/usrlocal/bin/zsh'

### vim
- git:
    repo: git@github.com:Shougo/neobundle.vim
    dest: ${HOME}/.vim/bundle/neobundle.vim
    version: master
    accept_hostkey: yes

- git:
    repo: git@github.com:tomasr/molokai
    dest: /tmp/molokai
    version: master
    accept_hostkey: yes

- name: set molokai file
  copy:
    src: /tmp/molokai/colors/molokai.vim
    dest: ${HOME}/.vim/colors/molokai.vim
